PhanMemChuyenDoiBaoCaoWeb/Models/Entity/Node.cs
using PhanMemChuyenDoiBaoCaoWeb.Models.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Xml;

namespace PhanMemChuyenDoiBaoCaoWeb.Models
{
    public class Node
    {

        private string name;
        private string path;
        private string oldValue;
        private string newValue;
        private List<AtrNode> listAttr;

        public Node(string name, List<AtrNode> listAttr, string path, string oldValue, string newValue)
        {
            Name = name;
            ListAttr = listAttr;
            Path = path;
            OldValue = oldValue;
            NewValue = newValue;
        }

        public string Name { get => name; set => name = value; }
        public string Path { get => path; set => path = value; }
        public string OldValue { get => oldValue; set => oldValue = value; }
        public string NewValue { get => newValue; set => newValue = value; }
        public List<AtrNode> ListAttr { get => listAttr; set => listAttr = value; }
    }
}

PhanMemChuyenDoiBaoCaoWeb/Controllers/NodeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using PhanMemChuyenDoiBaoCaoWeb.Models;
using PhanMemChuyenDoiBaoCaoWeb.Models.DAO;
using PhanMemChuyenDoiBaoCaoWeb.Models.Entity;
using PhanMemChuyenDoiBaoCaoWeb.Models.Service;
using PhanMemChuyenDoiBaoCaoWeb.Models.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Xml;

namespace PhanMemChuyenDoiBaoCaoWeb.Controllers
{
    public class NodeController : Controller
    {
        // GET: NodeController
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult DoiGiaTriTrongThe()
        {
            return View();
        }
        [HttpGet]
        public ActionResult CapNhatDuLieuThe(string inputFileEdit, string InputFileMaster)
        {
            Modules modules = new Modules();
            modules.InputFileEdit = inputFileEdit;
            modules.InputFileMaster = InputFileMaster;
            return View(modules);
        }

        // POST: NodeController/CapNhatDuLieuTheSubmit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CapNhatDuLieuTheSubmit(Modules modules)
        {
            try
            {
                NodeService nodeService = new NodeServiceImp();
                bool checkSaveFile = false;

                //Gọi service load file master
                XmlDocument rootMaster = nodeService.OpenFile(modules.InputFileMaster);

                //Goij service đọc tham số trong master
                Dictionary<string, string> variables = new Dictionary<string, string>();
                XmlNode variablesMaster = rootMaster.SelectSingleNode(VariableStatic.keyValues["selectNodeVariables"].Path);
                if(rootMaster.HasChildNodes)
                {
                    nodeService.DocThamSoGoc(variables, rootMaster);
                }

                foreach (var file in System.IO.Directory.GetFiles(modules.InputFileEdit))
                {
                    //Gọi service load file cần xử lý
                    XmlDocument root = nodeService.OpenFile(file);
                    //Thực hiện các chức năng
                    if(modules.DoiTenTruongCoDinh)
                    {
                        nodeService.DoiTenTruongCoDinh(file, root);
                    }
                    if(modules.CapNhatThamSo)
                    {
                        nodeService.DoiThamSo(file, root, rootMaster, variables, variablesMaster);
                    }
                    if(modules.DoiNhom)
                    {
                        nodeService.DoiNhom(file, root);
                    }
                    if(modules.ThemLienKetBang)
                    {
                        nodeService.ThemLienKetBang(file, root);
                    }
                    if(modules.ThemTheDuLieu)
                    {
                        nodeService.ThemTheDuLieu(file, root);
                    }
                    if(modules.SuaWatermark)
                    {
                        nodeService.SuaWatermark(file, root);
                    }
                    if(modules.SuaDatasource)
                    {
                        nodeService.SuaDatasource(file, root);
                    }
                    //Gọi service lưu file sau khi thực hiện các chức năng
                    checkSaveFile = nodeService.SaveFile(root, file);
                }
                if (checkSaveFile)
                {
                    return View("Index");
                }
                else
                {
                    return Content("Chưa xử lý");
                }
            }
            catch (Exception e)
            {
                return Content("Có lỗi xảy ra:\n"+ e);
            }
        }
        
    }
}

PhanMemChuyenDoiBaoCaoWeb/Views/Node/CapNhatDuLieuThe.cshtml
@{
    ViewData["Title"] = "Cập nhật dữ liệu thẻ";
}
@model PhanMemChuyenDoiBaoCaoWeb.Models.Entity.Modules
<form asp-action="CapNhatDuLieuTheSubmit" method="post" asp-controller="Node">
    <!--LẤY GIÁ TRỊ TRÊN URL-->
    <input type="text" value="@Model.InputFileEdit" name="InputFileEdit" hidden/>
    <input type="text" value="@Model.InputFileMaster" name="InputFileMaster" hidden/>
    <!--KÊT THÚC-->
    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <div class="input-group-text">
                <input asp-for="@Model.DoiTenTruongCoDinh" type="checkbox" name="DoiTenTruongCoDinh">
            </div>
        </div>
        <input type="text" class="form-control" value="Đổi tên trường cố định" readonly />
    </div>

    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <div class="input-group-text">
                <input asp-for="@Model.CapNhatThamSo" type="checkbox"  name="CapNhatThamSo">
            </div>
        </div>
        <input type="text" class="form-control" value="Cập nhật tham số" readonly />
    </div>

    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <div class="input-group-text">
                <input asp-for="@Model.DoiNhom" type="checkbox" name="DoiNhom">
            </div>
        </div>
        <input type="text" class="form-control" value="Đổi nhóm" readonly />
    </div>

    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <div class="input-group-text">
                <input asp-for="@Model.ThemLienKetBang" type="checkbox" name="ThemLienKetBang">
            </div>
        </div>
        <input type="text" class="form-control" value="Thêm liên kết bảng" readonly />
    </div>

    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <div class="input-group-text">
                <input asp-for="@Model.ThemTheDuLieu" type="checkbox" name="ThemTheDuLieu">
            </div>
        </div>
        <input type="text" class="form-control" value="Thêm thẻ dữ liệu" readonly />
    </div>

    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <div class="input-group-text">
                <input asp-for="@Model.SuaWatermark" type="checkbox" name="SuaWatermark">
            </div>
        </div>
        <input type="text" class="form-control" value="Sửa Watermark" readonly />
    </div>

    <div class="input-group mb-3">
        <div class="input-group-prepend">
            <div class="input-group-text">
                <input asp-for="@Model.SuaDatasource" type="checkbox" name="SuaDataSource">
            </div>
        </div>
        <input type="text" class="form-control" value="Sửa Data Source" readonly />
    </div>

    <button type="submit" class="btn btn-primary">Thực hiện</button>
</form>

PhanMemChuyenDoiBaoCaoWeb/Views/Node/DoiGiaTriTrongThe.cshtml
@{
    ViewData["Title"] = "Đổi giá trị trong thẻ";
}
<form>
    <table class="table table-hover table-bordered" id="myTable">
        <thead class="thead-light border text-center">
            <tr>
                <th>Tên thẻ</th>
                <th>Giá trị cũ</th>
                <th>Giá trị mới</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <input type="text" class="form-control" />
                </td>
                <td>
                    <input type="text" class="form-control" />
                </td>
                <td>
                    <input type="text" class="form-control" />
                </td>
            </tr>
        </tbody>
    </table>
    <div>
        <button type="submit" class="btn btn-primary">Thực hiện</button>
        <a href="#" class="btn btn-primary float-right" id="add-row">Thêm thẻ mới</a>
    </div>


</form>
<script>
    $(document).ready(function () {
        $("a").click(function () {
            alert("The paragraph was clicked.");
        });
    });
</script>

PhanMemChuyenDoiBaoCaoWeb/Views/Node/Index.cshtml
<form asp-action="CapNhatDuLieuThe" method="get" asp-controller="Node">
    <div class="form-group">
        <label for="inputFileEdit">Đưỡng dẫn đến files cần thực hiện</label>
        <input type="text" class="form-control" name="inputFileEdit">
    </div>
    <div class="form-group">
        <label for="inputFileMaster">Chọn file chứa tham số gốc</label>
        <input type="text" class="form-control" name="inputFileMaster">
    </div>
    <button type="submit" class="btn btn-primary">Tiếp tục</button>
</form>